### ISSUE TITLE
Support Gradle 2.1+ plugin id semantics

### ISSUE THREAD

**Issue by thatsIch** [riiid/gradle-github-plugin#1]
With later versions of Gradle you can use

```
plugins {
    id "<your unique ID>"
}
```

It just requires to be in the central plugin repo of Gradle. See https://plugins.gradle.org

**Comment by importre** [comment]
Nice suggestion!

I've uploaded it to plugins.gradle.org. See https://plugins.gradle.org/plugin/co.riiid.gradle
and updated [readme.md](https://github.com/riiid/gradle-github-plugin#2-pluginsgradleorg-easy)

Thank you.

**Comment by thatsIch** [comment]
Nice, thank you!
