### ISSUE TITLE
Asset upload failing

### ISSUE THREAD

**Issue by mangrish** [riiid/gradle-github-plugin#2]
Hi,

When I do an upload of a zip or tar asset generated from the application plugin I get the following response from github:

```
{message=missing ?url parameter or multipart form data, request_id=B4B5D185:2F09:A4CF6E6:56662C5F}
```

This is true whether it's from the application plugin or any other file.

The actual github release is actually done through. It's just the subsequent asset uploading that fails. I checked the mime type with your code and it does the right thing (in the zip case it's application/zip).

There isn't much debug code so I can't really tell you where the error is.

here is the config:

```
github {
    owner = 'xxx-xxx'
    repo = 'abc.abc.abc'
    token = 'XXXXXXXXXXXXXXXXXXX'
    tagName = 'v' + version
    name = 'Version ' + version
    body = 'Autogenerated by Gradle'
    assets = ['build/distributions/' + applicationName + '-' + version + '.zip']
}
```

the version var comes from the ch.netzwerg.release plugin.

**Comment by mangrish** [comment]
Ergh.. nevermind. The version of the library on your documentation page is out of date. It says version 0.3.0. I upgraded it to 0.3.1 and it's all fine now!

**Comment by importre** [comment]
Oops. Thank you for your report.
I've fixed it. https://github.com/riiid/gradle-github-plugin/commit/976259856ebb149881d172e1cbf798cd1f0e22ad :tada:
